myproject/myproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), #追加
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'), #追加
]

myproject/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),  # 追加
    path('', include('accounts.urls')),  # "追加"
    path('admin/', admin.site.urls),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sendmail.urls', namespace='sendmail')),
    path('sendmail/', include('sendmail.urls')), #"追加"
    path('admin/', admin.site.urls),
]

myproject/sendmail/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'sendmail'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
]

myproject/myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/sendmail/models.py
from django.db import models

# Create your models here.

myproject/myproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy


class index(LoginRequiredMixin, generic.TemplateView):
    """メニュービュー"""
    template_name = 'accounts/top.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # 継承元のメソッドCALL
        context["form_name"] = "top"
        return context


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    """パスワード変更ビュー"""
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # 継承元のメソッドCALL
        context["form_name"] = "password_change"
        return context


class PasswordChangeDone(LoginRequiredMixin,PasswordChangeDoneView):
    """パスワード変更完了"""
    template_name = 'accounts/password_change_done.html'

myproject/sendmail/views.py
from django.core.mail import EmailMessage
from django.http import HttpResponse


def index(request):
   EmailMessage(u'メールテスト', u'Hello World', to=['kzk0802kazuki@gmail.com', 'kzk0802kazuki@gmail.com']).send()
   return HttpResponse('Send your register email')

myproject/myproject/templates/accounts/password_change.html
{% extends "commons/base.html" %}

{% block title %}パスワード変更{% endblock %}

{% block styles %}
{% endblock %}

{% block headertitle %}パスワード変更{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
<div  class="col-6">
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label class="col-6" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="form-group row">
      <div class="col-sm">
        <button type="submit" class="btn btn-primary btn-block">送信</button>
      </div>
      <div class="col-sm">
        <button type="submit" class="btn btn-primary btn-block" onClick="javascript:history.go(-1);">戻る</button>
      </div>
    </div>
</form>
</div>
</div>
{% endblock %}

myproject/myproject/templates/accounts/password_change_done.html
{% extends "commons/base.html" %}

{% block title %}パスワード変更完了{% endblock %}

{% block styles %}
{% endblock %}

{% block headertitle %}パスワード変更完了{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div  class="col-4">
    <p>パスワードを変更しました。</p>
    <div class="form-group row">
      <div class="col-6">
        <a class="btn btn-primary btn-block" href="{% url 'accounts:index' %}">トップへ</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myproject/myproject/templates/accounts/top.html
{% extends "commons/base.html" %}

{% block title %}メニュー{% endblock %}

{% block styles %}
nav.menu ul li {
    list-style-type:none;
    font-size: 1.1em;
}
{% endblock %}

{% block headertitle %}メニュー画面{% endblock %}

{% block content %}
<nav class="menu">
  <ul>
      <li>
        <a target="_blank" href="/hello">Hello World!</a>
      </li>
  </ul>
</nav>
{% endblock %}

{% block scripts %}
<script>
</script>
{% endblock %}

myproject/myproject/templates/commons/base.html
{% load staticfiles %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <style>
        body {
          padding : 10px;
        }
        div.container {
          min-width:600px;
        }
        nav ul#menu {
            margin:0px;
            padding:0px;
        }
        nav ul#menu li {
            float:right;
            list-style-type:none;
            text-decoration: underline;
            padding-left: 10px;
        }
        div.header {
          padding: 10px;
        }
        div.header * {
          color: white !important;
        }
        div.header .title {
          font-size: 1.2em;
        }
        {% block styles %}{% endblock %}
    </style>
</head>
<body>
<div class="container">
  <div class="inner">
    <div class="text-right">{{ form_name }}</div>
    <div class="row header mysystem-header">
      <div class="col-sm title">
        {% block headertitle %}{% endblock %}
      </div>
      <div class="col-sm">
        <nav class="pull-right">
            <ul id="menu">
              {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">ログアウト</a></li>
                {% if form_name == "password_change" %}
                {% else %}
                    <li><a href="{% url 'accounts:password_change' %}" class="logout">パスワードの変更</a></li>
                {% endif %}
              {% else %}
              {% endif %}
            </ul>
        </nav>
      </div>
    </div>
    <br/>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
  </div>
</div>

<script src="{% static "js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>